import type { Company } from "./types";

export const COMPANIES: Company[] = [
  {
    "n": "Jugemu.ai",
    "c": "Saratoga",
    "lat": 37.2638,
    "lng": -122.023,
    "i": "MarTech/AI",
    "e": null,
    "m": 22,
    "g": 10,
    "x": 11,
    "z": 8,
    "hs": 0,
    "w": null,
    "k": "Marketing is the product itself -- high day-one relevance, but no confirmed opening; pitch a specific contribution",
    "desc": "AI automating customer acquisition/bot mitigation (web3)"
  },
  {
    "n": "Flick",
    "c": "Sunnyvale",
    "lat": 37.3688,
    "lng": -122.0363,
    "i": "Consumer/AI",
    "e": null,
    "m": 18,
    "g": 14,
    "x": 15,
    "z": 8,
    "hs": 0,
    "w": "flick.art",
    "k": "Active press/LinkedIn coverage",
    "desc": "AI filmmaking studio/tool for directors"
  },
  {
    "n": "Jobright",
    "c": "Santa Clara",
    "lat": 37.3541,
    "lng": -121.9552,
    "i": "Consumer/AI",
    "e": null,
    "m": 18,
    "g": 10,
    "x": 11,
    "z": 8,
    "hs": 0,
    "w": "jobright.ai",
    "k": "Consumer product with active app/site",
    "desc": "AI job-search assistant/recommendation platform"
  },
  {
    "n": "Wanderboat AI",
    "c": "Sunnyvale",
    "lat": 37.3688,
    "lng": -122.0363,
    "i": "Consumer/AI",
    "e": "30",
    "m": 18,
    "g": 10,
    "x": 15,
    "z": 8,
    "hs": 0,
    "w": "wanderboat.ai",
    "k": "Visual Designer listed; weaker signal",
    "desc": "AI travel-planning companion"
  },
  {
    "n": "Janet AI",
    "c": "Saratoga",
    "lat": 37.2638,
    "lng": -122.023,
    "i": "Business Software/AI",
    "e": null,
    "m": 12,
    "g": 14,
    "x": 11,
    "z": 8,
    "hs": 0,
    "w": "tryjanet.ai",
    "k": "No specific marketing signal found this pass -- check their site and socials before writing the email",
    "desc": "AI-native support-ticket management system"
  },
  {
    "n": "ParkStash",
    "c": "San Jose",
    "lat": 37.3382,
    "lng": -121.8863,
    "i": "PropTech/SaaS",
    "e": null,
    "m": 12,
    "g": 10,
    "x": 15,
    "z": 8,
    "hs": 0,
    "w": "findparkstash.com",
    "k": "No specific marketing signal found this pass -- check their site and socials before writing the email",
    "desc": "Digital parking permits/enforcement for property managers"
  },
  {
    "n": "Lollipuff",
    "c": "Mountain View",
    "lat": 37.3861,
    "lng": -122.0839,
    "i": "E-commerce/Consumer",
    "e": "11",
    "m": 18,
    "g": 9,
    "x": 11,
    "z": 9,
    "hs": 0,
    "w": "lollipuff.com",
    "k": "Team this small very likely has no dedicated marketer yet (unconfirmed) -- worth checking their site/socials directly",
    "desc": "Authenticated luxury pre-owned fashion auctions"
  },
  {
    "n": "Rulai",
    "c": "Campbell",
    "lat": 37.2872,
    "lng": -121.95,
    "i": "Business Software/AI",
    "e": "15",
    "m": 12,
    "g": 10,
    "x": 11,
    "z": 9,
    "hs": 0,
    "w": "rul.ai",
    "k": "No specific marketing signal found this pass -- check their site and socials before writing the email",
    "desc": "AI-powered enterprise chatbot platform"
  },
  {
    "n": "AiPrise",
    "c": "San Jose",
    "lat": 37.3382,
    "lng": -121.8863,
    "i": "Fintech/AI",
    "e": null,
    "m": 12,
    "g": 10,
    "x": 11,
    "z": 8,
    "hs": 0,
    "w": "aiprise.com",
    "k": "'Trusted by 200+ compliance teams' (own claim)",
    "desc": "Identity verification/fraud-detection APIs"
  },
  {
    "n": "Metazoa",
    "c": "Los Gatos",
    "lat": 37.2358,
    "lng": -121.9624,
    "i": "Business Software/SaaS",
    "e": null,
    "m": 12,
    "g": 10,
    "x": 11,
    "z": 8,
    "hs": 0,
    "w": "metazoa.com",
    "k": "No specific marketing signal found this pass -- check their site and socials before writing the email",
    "desc": "Salesforce admin change-management tool"
  },
  {
    "n": "Brevian",
    "c": "Sunnyvale",
    "lat": 37.3688,
    "lng": -122.0363,
    "i": "Business Software/AI",
    "e": null,
    "m": 12,
    "g": 14,
    "x": 11,
    "z": 8,
    "hs": 0,
    "w": "brevian.ai",
    "k": "TechCrunch launch coverage",
    "desc": "No-code enterprise platform for building AI agents"
  },
  {
    "n": "Nexxa.ai",
    "c": "Sunnyvale",
    "lat": 37.3688,
    "lng": -122.0363,
    "i": "Business Software/AI",
    "e": null,
    "m": 12,
    "g": 14,
    "x": 11,
    "z": 8,
    "hs": 0,
    "w": "nexxa.ai",
    "k": "No specific marketing signal found this pass -- check their site and socials before writing the email",
    "desc": "AI multi-agent automation for heavy industries"
  },
  {
    "n": "Novaworks.ai",
    "c": "Los Gatos",
    "lat": 37.2358,
    "lng": -121.9624,
    "i": "Business Software/AI",
    "e": null,
    "m": 12,
    "g": 15,
    "x": 5,
    "z": 8,
    "hs": 0,
    "w": "novaworks.ai",
    "k": "Actively hiring; PR-launched product",
    "desc": "Agentic AI HCM/workforce-management OS on ServiceNow"
  },
  {
    "n": "CLARA Analytics",
    "c": "Santa Clara",
    "lat": 37.3541,
    "lng": -121.9552,
    "i": "Fintech/AI",
    "e": "61",
    "m": 12,
    "g": 10,
    "x": 11,
    "z": 6,
    "hs": 0,
    "w": "claraanalytics.com",
    "k": "Active site, Built In SF profile",
    "desc": "AI for insurance claims (doc intel, fraud)"
  },
  {
    "n": "Altimate AI",
    "c": "Sunnyvale",
    "lat": 37.3688,
    "lng": -122.0363,
    "i": "DevTools/AI",
    "e": "30",
    "m": 10,
    "g": 10,
    "x": 15,
    "z": 8,
    "hs": 0,
    "w": "altimate.ai",
    "k": "Digital Marketing Specialist (AEO/SEO) role open",
    "desc": "Data/AI analytics tooling"
  },
  {
    "n": "Billion Dollar Startup Ideas",
    "c": "Remote",
    "lat": null,
    "lng": null,
    "i": "Media/Content",
    "e": null,
    "m": 18,
    "g": 10,
    "x": 11,
    "z": 8,
    "hs": 0,
    "w": "billiondollarstartupideas.com",
    "k": "Ladder partner; explicitly invites contributors; strong content-role fit",
    "desc": "Startup-idea media/newsletter + consulting"
  },
  {
    "n": "Feedly",
    "c": "Redwood City",
    "lat": 37.4852,
    "lng": -122.2364,
    "i": "Productivity/AI",
    "e": "30",
    "m": 15,
    "g": 10,
    "x": 15,
    "z": 8,
    "hs": 0,
    "w": "feedly.com",
    "k": "CS Manager listed; weaker marketing signal",
    "desc": "AI-powered content/news reader"
  },
  {
    "n": "Lapis",
    "c": "San Francisco",
    "lat": 37.7749,
    "lng": -122.4194,
    "i": "MarTech/AI",
    "e": "5",
    "m": 25,
    "g": 14,
    "x": 11,
    "z": 10,
    "hs": 0,
    "w": "trylapis.com",
    "k": "Serves 1,500+ marketing teams (launch post)",
    "desc": "AI creates/runs ad campaigns end-to-end"
  },
  {
    "n": "Reacher",
    "c": "San Francisco",
    "lat": 37.7749,
    "lng": -122.4194,
    "i": "MarTech/AI",
    "e": "10",
    "m": 25,
    "g": 14,
    "x": 11,
    "z": 9,
    "hs": 0,
    "w": "reacherapp.com",
    "k": "Core product is influencer marketing automation",
    "desc": "AI creator-marketing workflow automation"
  },
  {
    "n": "Gauge",
    "c": "San Francisco",
    "lat": 37.7749,
    "lng": -122.4194,
    "i": "MarTech/AI",
    "e": "5",
    "m": 22,
    "g": 14,
    "x": 11,
    "z": 10,
    "hs": 0,
    "w": "withgauge.com",
    "k": "Marketing is the product itself -- high day-one relevance, but no confirmed opening; pitch a specific contribution",
    "desc": "Tests how AI agents recommend products"
  },
  {
    "n": "GetCrux",
    "c": "San Francisco",
    "lat": 37.7749,
    "lng": -122.4194,
    "i": "MarTech/AI",
    "e": "9",
    "m": 22,
    "g": 14,
    "x": 11,
    "z": 10,
    "hs": 0,
    "w": "getcrux.ai",
    "k": "Marketing is the product itself -- high day-one relevance, but no confirmed opening; pitch a specific contribution",
    "desc": "AI ad-creative strategist/analytics"
  },
  {
    "n": "Gooseworks",
    "c": "San Francisco",
    "lat": 37.7749,
    "lng": -122.4194,
    "i": "MarTech/AI",
    "e": "5",
    "m": 22,
    "g": 14,
    "x": 11,
    "z": 10,
    "hs": 0,
    "w": "gooseworks.ai",
    "k": "Marketing is the product itself -- high day-one relevance, but no confirmed opening; pitch a specific contribution",
    "desc": "AI ad-creative engine for Meta/TikTok"
  },
  {
    "n": "LemonLime",
    "c": "San Francisco",
    "lat": 37.7749,
    "lng": -122.4194,
    "i": "MarTech/AI",
    "e": "5",
    "m": 22,
    "g": 14,
    "x": 11,
    "z": 10,
    "hs": 0,
    "w": "lemonlime.com",
    "k": "Marketing is the product itself -- high day-one relevance, but no confirmed opening; pitch a specific contribution",
    "desc": "Automated sales/marketing platform for small businesses"
  },
  {
    "n": "Meta2 Labs",
    "c": "Remote",
    "lat": null,
    "lng": null,
    "i": "Business Software",
    "e": null,
    "m": 15,
    "g": 10,
    "x": 5,
    "z": 8,
    "hs": 5,
    "w": null,
    "k": "'No experience required', no college requirement, remote/unpaid marketing intern",
    "desc": "Enterprise software for SMBs"
  },
  {
    "n": "Spikeview",
    "c": "Remote",
    "lat": null,
    "lng": null,
    "i": "EdTech",
    "e": null,
    "m": 15,
    "g": 10,
    "x": 5,
    "z": 8,
    "hs": 5,
    "w": "spikeview.com",
    "k": "Careers page explicitly labels roles 'High school intern eligible' (Content Creator, Social Media Manager, Partnership Manager)",
    "desc": "K-12 digital portfolio/career-readiness platform"
  },
  {
    "n": "Surface Labs",
    "c": "San Francisco",
    "lat": 37.7749,
    "lng": -122.4194,
    "i": "MarTech/AI",
    "e": "6",
    "m": 22,
    "g": 14,
    "x": 11,
    "z": 10,
    "hs": 0,
    "w": "withsurface.com",
    "k": "Marketing is the product itself -- high day-one relevance, but no confirmed opening; pitch a specific contribution",
    "desc": "AI marketing-ops smart forms/lead qual"
  },
  {
    "n": "The Prompting Company",
    "c": "San Francisco",
    "lat": 37.7749,
    "lng": -122.4194,
    "i": "MarTech/AI",
    "e": "7",
    "m": 22,
    "g": 14,
    "x": 11,
    "z": 10,
    "hs": 0,
    "w": "promptingcompany.com",
    "k": "Marketing is the product itself -- high day-one relevance, but no confirmed opening; pitch a specific contribution",
    "desc": "AI discoverability/SEO for AI agents"
  },
  {
    "n": "zime.ai",
    "c": "Palo Alto",
    "lat": 37.4419,
    "lng": -122.143,
    "i": "Business Software/AI",
    "e": "30",
    "m": 12,
    "g": 10,
    "x": 15,
    "z": 8,
    "hs": 0,
    "w": "zime.ai",
    "k": "BDR (Field & Events) role open",
    "desc": "Behavioral-science-driven AI product"
  },
  {
    "n": "1stCollab",
    "c": "San Francisco",
    "lat": 37.7749,
    "lng": -122.4194,
    "i": "MarTech/AI",
    "e": "11",
    "m": 22,
    "g": 14,
    "x": 11,
    "z": 9,
    "hs": 0,
    "w": "1stcollab.com",
    "k": "Marketing is the product itself -- high day-one relevance, but no confirmed opening; pitch a specific contribution",
    "desc": "AI influencer-marketing automation"
  },
  {
    "n": "ApertureData",
    "c": "Los Gatos",
    "lat": 37.2358,
    "lng": -121.9624,
    "i": "DevTools/Data",
    "e": null,
    "m": 8,
    "g": 10,
    "x": 11,
    "z": 8,
    "hs": 0,
    "w": "aperturedata.io",
    "k": "No specific marketing signal found this pass -- check their site and socials before writing the email",
    "desc": "Database for multimodal AI development"
  },
  {
    "n": "Ascenium",
    "c": "Campbell",
    "lat": 37.2872,
    "lng": -121.95,
    "i": "DeepTech/Semiconductor",
    "e": null,
    "m": 8,
    "g": 10,
    "x": 11,
    "z": 8,
    "hs": 0,
    "w": "ascenium.com",
    "k": "No specific marketing signal found this pass -- check their site and socials before writing the email",
    "desc": "Fabless semiconductor startup - general-purpose microprocessor"
  },
  {
    "n": "AthenaHQ",
    "c": "San Francisco",
    "lat": 37.7749,
    "lng": -122.4194,
    "i": "MarTech/AI",
    "e": "12",
    "m": 22,
    "g": 14,
    "x": 11,
    "z": 9,
    "hs": 0,
    "w": "athenahq.ai",
    "k": "Marketing is the product itself -- high day-one relevance, but no confirmed opening; pitch a specific contribution",
    "desc": "AI/GEO brand-visibility tracking"
  },
  {
    "n": "Aurva",
    "c": "Sunnyvale",
    "lat": 37.3688,
    "lng": -122.0363,
    "i": "DevTools/Security",
    "e": null,
    "m": 8,
    "g": 14,
    "x": 11,
    "z": 8,
    "hs": 0,
    "w": "aurva.io",
    "k": "Case studies (Razorpay, Meesho)",
    "desc": "AI runtime data-security/DSPM platform"
  },
  {
    "n": "Bench AI",
    "c": "San Jose",
    "lat": 37.3382,
    "lng": -121.8863,
    "i": "DevTools/AI",
    "e": "2",
    "m": 8,
    "g": 10,
    "x": 11,
    "z": 10,
    "hs": 0,
    "w": "bench-ai.com",
    "k": "Team this small very likely has no dedicated marketer yet (unconfirmed) -- worth checking their site/socials directly",
    "desc": "Simplified MLOps SDK, no cloud config needed"
  },
  {
    "n": "CatchBack Cards",
    "c": "San Francisco",
    "lat": 37.7749,
    "lng": -122.4194,
    "i": "Consumer",
    "e": "7",
    "m": 20,
    "g": 15,
    "x": 11,
    "z": 10,
    "hs": 0,
    "w": "catchbackcards.com",
    "k": "Hiring GTM/Growth Intern & Social Media Manager; launched Jan 2026",
    "desc": "App for digital collectible card packs"
  },
  {
    "n": "Conformiq",
    "c": "Saratoga",
    "lat": 37.2638,
    "lng": -122.023,
    "i": "DevTools/SaaS",
    "e": null,
    "m": 8,
    "g": 10,
    "x": 11,
    "z": 8,
    "hs": 0,
    "w": null,
    "k": "No specific marketing signal found this pass -- check their site and socials before writing the email",
    "desc": "Model-based automated software test design"
  },
  {
    "n": "Dymium",
    "c": "Los Gatos",
    "lat": 37.2358,
    "lng": -121.9624,
    "i": "Security/SaaS",
    "e": null,
    "m": 8,
    "g": 10,
    "x": 11,
    "z": 8,
    "hs": 0,
    "w": null,
    "k": "No specific marketing signal found this pass -- check their site and socials before writing the email",
    "desc": "Zero-trust data security/access management"
  },
  {
    "n": "Eliyan",
    "c": "Santa Clara",
    "lat": 37.3541,
    "lng": -121.9552,
    "i": "DeepTech/Semiconductor",
    "e": null,
    "m": 8,
    "g": 8,
    "x": 15,
    "z": 8,
    "hs": 0,
    "w": "eliyan.com",
    "k": "No specific marketing signal found this pass -- check their site and socials before writing the email",
    "desc": "Semiconductor chip-to-chip interconnect (UCIe) tech"
  },
  {
    "n": "Elumn8 Medical",
    "c": "Campbell",
    "lat": 37.2872,
    "lng": -121.95,
    "i": "MedTech",
    "e": null,
    "m": 8,
    "g": 10,
    "x": 11,
    "z": 8,
    "hs": 0,
    "w": null,
    "k": "No specific marketing signal found this pass -- check their site and socials before writing the email",
    "desc": "Medical automation/visualization devices"
  },
  {
    "n": "Ferveret",
    "c": "San Jose",
    "lat": 37.3382,
    "lng": -121.8863,
    "i": "DeepTech/Hardware",
    "e": "6",
    "m": 8,
    "g": 10,
    "x": 11,
    "z": 10,
    "hs": 0,
    "w": "ferveret.com",
    "k": "Press coverage (BusinessWire)",
    "desc": "Waterless/adaptive-phase liquid cooling for data centers"
  },
  {
    "n": "FriendliAI",
    "c": "Redwood City",
    "lat": 37.4852,
    "lng": -122.2364,
    "i": "DevTools/AI",
    "e": null,
    "m": 8,
    "g": 14,
    "x": 15,
    "z": 8,
    "hs": 0,
    "w": "friendli.ai",
    "k": "New SF office announced; active careers page",
    "desc": "GenAI model-serving/inference infra"
  },
  {
    "n": "Hyphen",
    "c": "San Jose",
    "lat": 37.3382,
    "lng": -121.8863,
    "i": "FoodTech/Robotics",
    "e": null,
    "m": 8,
    "g": 10,
    "x": 11,
    "z": 8,
    "hs": 0,
    "w": "usehyphen.com",
    "k": "Featured in AgFunderNews founder interview",
    "desc": "Robotic food-prep systems (used by Chipotle)"
  },
  {
    "n": "Laredo Labs",
    "c": "San Jose",
    "lat": 37.3382,
    "lng": -121.8863,
    "i": "DevTools/AI",
    "e": null,
    "m": 8,
    "g": 14,
    "x": 15,
    "z": 8,
    "hs": 0,
    "w": "laredolabs.ai",
    "k": "No specific marketing signal found this pass -- check their site and socials before writing the email",
    "desc": "GenAI tool to automate developer workflows"
  },
  {
    "n": "Maven Robotics",
    "c": "Santa Clara",
    "lat": 37.3541,
    "lng": -121.9552,
    "i": "Robotics/AI",
    "e": null,
    "m": 8,
    "g": 10,
    "x": 11,
    "z": 8,
    "hs": 0,
    "w": null,
    "k": "No specific marketing signal found this pass -- check their site and socials before writing the email",
    "desc": "General-purpose industrial AI robots"
  },
  {
    "n": "Pave Robotics",
    "c": "San Jose",
    "lat": 37.3382,
    "lng": -121.8863,
    "i": "Robotics/AI",
    "e": "5",
    "m": 8,
    "g": 10,
    "x": 15,
    "z": 10,
    "hs": 0,
    "w": "pave-robotics.com",
    "k": "Team this small very likely has no dedicated marketer yet (unconfirmed) -- worth checking their site/socials directly",
    "desc": "Robots that seal asphalt cracks/repair roads"
  },
  {
    "n": "Podonos",
    "c": "Los Gatos",
    "lat": 37.2358,
    "lng": -121.9624,
    "i": "DevTools/AI",
    "e": null,
    "m": 8,
    "g": 10,
    "x": 11,
    "z": 8,
    "hs": 0,
    "w": null,
    "k": "No specific marketing signal found this pass -- check their site and socials before writing the email",
    "desc": "AI model evaluation-as-a-service"
  },
  {
    "n": "PuppyGraph",
    "c": "Santa Clara",
    "lat": 37.3541,
    "lng": -121.9552,
    "i": "DevTools/Data",
    "e": null,
    "m": 8,
    "g": 10,
    "x": 11,
    "z": 8,
    "hs": 0,
    "w": "puppygraph.com",
    "k": "Customer testimonials on site",
    "desc": "Graph analytics engine for data lakes"
  },
  {
    "n": "Refiberd",
    "c": "Cupertino",
    "lat": 37.323,
    "lng": -122.0322,
    "i": "CleanTech/AI",
    "e": null,
    "m": 8,
    "g": 10,
    "x": 11,
    "z": 8,
    "hs": 0,
    "w": "refiberd.com",
    "k": "No specific marketing signal found this pass -- check their site and socials before writing the email",
    "desc": "AI + robotics textile-sorting/recycling system"
  },
  {
    "n": "Reka AI",
    "c": "Sunnyvale",
    "lat": 37.3688,
    "lng": -122.0363,
    "i": "AI/Infra",
    "e": null,
    "m": 8,
    "g": 8,
    "x": 15,
    "z": 8,
    "hs": 0,
    "w": "reka.ai",
    "k": "No specific marketing signal found this pass -- check their site and socials before writing the email",
    "desc": "Multimodal generative AI (vision, speech)"
  },
  {
    "n": "Relcu",
    "c": "Saratoga",
    "lat": 37.2638,
    "lng": -122.023,
    "i": "Fintech/SaaS",
    "e": "4",
    "m": 8,
    "g": 10,
    "x": 11,
    "z": 10,
    "hs": 0,
    "w": "relcu.com",
    "k": "Team this small very likely has no dedicated marketer yet (unconfirmed) -- worth checking their site/socials directly",
    "desc": "Mortgage-industry CRM software"
  },
  {
    "n": "Retym",
    "c": "Cupertino",
    "lat": 37.323,
    "lng": -122.0322,
    "i": "DeepTech/Semiconductor",
    "e": null,
    "m": 8,
    "g": 10,
    "x": 11,
    "z": 8,
    "hs": 0,
    "w": "retym.com",
    "k": "No specific marketing signal found this pass -- check their site and socials before writing the email",
    "desc": "Semiconductor tech for data centers/telecom"
  },
  {
    "n": "Selera Medical",
    "c": "Mountain View",
    "lat": 37.3861,
    "lng": -122.0839,
    "i": "MedTech",
    "e": null,
    "m": 8,
    "g": 14,
    "x": 11,
    "z": 8,
    "hs": 0,
    "w": null,
    "k": "No specific marketing signal found this pass -- check their site and socials before writing the email",
    "desc": "Device-based treatment for heart failure"
  },
  {
    "n": "Straiker",
    "c": "Sunnyvale",
    "lat": 37.3688,
    "lng": -122.0363,
    "i": "Security/AI",
    "e": null,
    "m": 8,
    "g": 10,
    "x": 11,
    "z": 8,
    "hs": 0,
    "w": "straiker.net",
    "k": "No specific marketing signal found this pass -- check their site and socials before writing the email",
    "desc": "AI-native cybersecurity (runtime + red-teaming)"
  },
  {
    "n": "Syncly",
    "c": "San Francisco",
    "lat": 37.7749,
    "lng": -122.4194,
    "i": "MarTech/AI",
    "e": "15",
    "m": 22,
    "g": 14,
    "x": 11,
    "z": 9,
    "hs": 0,
    "w": "syncly.app",
    "k": "Marketing is the product itself -- high day-one relevance, but no confirmed opening; pitch a specific contribution",
    "desc": "AI social listening for creator marketing"
  },
  {
    "n": "Vitesse Automation",
    "c": "Los Gatos",
    "lat": 37.2358,
    "lng": -121.9624,
    "i": "Robotics/AI",
    "e": null,
    "m": 8,
    "g": 10,
    "x": 11,
    "z": 8,
    "hs": 0,
    "w": "vitesseautomation.com",
    "k": "No specific marketing signal found this pass -- check their site and socials before writing the email",
    "desc": "'Physical AI' platform connecting industrial machines"
  },
  {
    "n": "Julius AI",
    "c": "San Francisco",
    "lat": 37.7749,
    "lng": -122.4194,
    "i": "Productivity/AI",
    "e": "8",
    "m": 15,
    "g": 15,
    "x": 15,
    "z": 10,
    "hs": 0,
    "w": "julius.ai",
    "k": "Growth Marketer role open",
    "desc": "AI data-analysis assistant"
  },
  {
    "n": "Miravoice",
    "c": "San Francisco",
    "lat": 37.7749,
    "lng": -122.4194,
    "i": "MarTech/AI",
    "e": null,
    "m": 22,
    "g": 14,
    "x": 11,
    "z": 8,
    "hs": 0,
    "w": "miravoice.com",
    "k": "Marketing is the product itself -- high day-one relevance, but no confirmed opening; pitch a specific contribution",
    "desc": "AI voice agents for phone surveys/market research"
  },
  {
    "n": "Scrollmark",
    "c": "San Francisco",
    "lat": 37.7749,
    "lng": -122.4194,
    "i": "MarTech/AI",
    "e": null,
    "m": 22,
    "g": 10,
    "x": 15,
    "z": 8,
    "hs": 0,
    "w": "scrollmark.com",
    "k": "Hiring Founding Data Scientist",
    "desc": "Social media intelligence/SocialGPT"
  },
  {
    "n": "ServiceUp",
    "c": "Los Gatos",
    "lat": 37.2358,
    "lng": -121.9624,
    "i": "Consumer/AI",
    "e": "125",
    "m": 18,
    "g": 4,
    "x": 5,
    "z": 4,
    "hs": 0,
    "w": "serviceup.com",
    "k": "Sunnyvale Chamber of Commerce feature",
    "desc": "AI-agent-run auto/fleet repair platform"
  },
  {
    "n": "Human Archive",
    "c": "Mountain View",
    "lat": 37.3861,
    "lng": -122.0839,
    "i": "AI/Infra",
    "e": "75",
    "m": 8,
    "g": 10,
    "x": 11,
    "z": 6,
    "hs": 0,
    "w": null,
    "k": "No specific marketing signal found this pass -- check their site and socials before writing the email",
    "desc": "Human-data archiving platform for embodied AI/robotics"
  },
  {
    "n": "SellRaze",
    "c": "San Francisco",
    "lat": 37.7749,
    "lng": -122.4194,
    "i": "E-commerce/AI",
    "e": "6",
    "m": 18,
    "g": 15,
    "x": 11,
    "z": 10,
    "hs": 0,
    "w": "sellraze.com",
    "k": "Fast revenue growth",
    "desc": "AI selling assistant across marketplaces"
  },
  {
    "n": "AirCaps",
    "c": "San Francisco",
    "lat": 37.7749,
    "lng": -122.4194,
    "i": "Consumer/AI",
    "e": "5",
    "m": 18,
    "g": 14,
    "x": 11,
    "z": 10,
    "hs": 0,
    "w": "aircaps.com",
    "k": "Team this small very likely has no dedicated marketer yet (unconfirmed) -- worth checking their site/socials directly",
    "desc": "AR-glasses live captions/translation/notes"
  },
  {
    "n": "Anglera",
    "c": "San Francisco",
    "lat": 37.7749,
    "lng": -122.4194,
    "i": "E-commerce/AI",
    "e": "6",
    "m": 18,
    "g": 14,
    "x": 11,
    "z": 10,
    "hs": 0,
    "w": "anglera.com",
    "k": "Team this small very likely has no dedicated marketer yet (unconfirmed) -- worth checking their site/socials directly",
    "desc": "AI product-data enrichment for e-commerce"
  },
  {
    "n": "Certus AI",
    "c": "San Francisco",
    "lat": 37.7749,
    "lng": -122.4194,
    "i": "Consumer/AI",
    "e": "8",
    "m": 18,
    "g": 14,
    "x": 11,
    "z": 10,
    "hs": 0,
    "w": "certus-ai.com",
    "k": "Team this small very likely has no dedicated marketer yet (unconfirmed) -- worth checking their site/socials directly",
    "desc": "AI voice agent for restaurant phone orders"
  },
  {
    "n": "Ditto",
    "c": "San Francisco",
    "lat": 37.7749,
    "lng": -122.4194,
    "i": "Consumer/AI",
    "e": "30",
    "m": 20,
    "g": 10,
    "x": 15,
    "z": 8,
    "hs": 0,
    "w": "ditto.ai",
    "k": "Head of Marketing role open",
    "desc": "Gen Z AI dating/matchmaking app"
  },
  {
    "n": "Drafted",
    "c": "San Francisco",
    "lat": 37.7749,
    "lng": -122.4194,
    "i": "Consumer/AI",
    "e": "9",
    "m": 18,
    "g": 14,
    "x": 11,
    "z": 10,
    "hs": 0,
    "w": "drafted.ai",
    "k": "Team this small very likely has no dedicated marketer yet (unconfirmed) -- worth checking their site/socials directly",
    "desc": "AI residential floor-plan generation app"
  },
  {
    "n": "Flow Club",
    "c": "San Francisco",
    "lat": 37.7749,
    "lng": -122.4194,
    "i": "Consumer/Productivity",
    "e": "6",
    "m": 18,
    "g": 14,
    "x": 11,
    "z": 10,
    "hs": 0,
    "w": "flow.club",
    "k": "Team this small very likely has no dedicated marketer yet (unconfirmed) -- worth checking their site/socials directly",
    "desc": "Virtual co-working/focus-sprint platform"
  },
  {
    "n": "Fort",
    "c": "San Francisco",
    "lat": 37.7749,
    "lng": -122.4194,
    "i": "Consumer/Hardware",
    "e": "4",
    "m": 18,
    "g": 14,
    "x": 11,
    "z": 10,
    "hs": 0,
    "w": "fort.cx",
    "k": "Team this small very likely has no dedicated marketer yet (unconfirmed) -- worth checking their site/socials directly",
    "desc": "Screenless wearable tracking strength training"
  },
  {
    "n": "Koyal",
    "c": "San Francisco",
    "lat": 37.7749,
    "lng": -122.4194,
    "i": "Consumer/AI",
    "e": "5",
    "m": 18,
    "g": 14,
    "x": 11,
    "z": 10,
    "hs": 0,
    "w": "koyal.ai",
    "k": "Team this small very likely has no dedicated marketer yet (unconfirmed) -- worth checking their site/socials directly",
    "desc": "Agentic AI filmmaking (script/audio to video)"
  },
  {
    "n": "OneText",
    "c": "San Francisco",
    "lat": 37.7749,
    "lng": -122.4194,
    "i": "E-commerce/Fintech",
    "e": "6",
    "m": 18,
    "g": 14,
    "x": 11,
    "z": 10,
    "hs": 0,
    "w": "onetext.com",
    "k": "Team this small very likely has no dedicated marketer yet (unconfirmed) -- worth checking their site/socials directly",
    "desc": "SMS one-text checkout for DTC brands"
  },
  {
    "n": "Pax Historia",
    "c": "San Francisco",
    "lat": 37.7749,
    "lng": -122.4194,
    "i": "Consumer/AI",
    "e": "6",
    "m": 18,
    "g": 14,
    "x": 11,
    "z": 10,
    "hs": 0,
    "w": "paxhistoria.co",
    "k": "Team this small very likely has no dedicated marketer yet (unconfirmed) -- worth checking their site/socials directly",
    "desc": "AI worldbuilding/sandbox gameplay platform"
  },
  {
    "n": "Vectara",
    "c": "Palo Alto",
    "lat": 37.4419,
    "lng": -122.143,
    "i": "DevTools/AI",
    "e": null,
    "m": 8,
    "g": 10,
    "x": 15,
    "z": 8,
    "hs": 0,
    "w": "vectara.com",
    "k": "Broadcom case study",
    "desc": "Enterprise AI agent/RAG platform"
  },
  {
    "n": "Constella",
    "c": "San Francisco",
    "lat": 37.7749,
    "lng": -122.4194,
    "i": "Productivity/AI",
    "e": "8",
    "m": 15,
    "g": 12,
    "x": 15,
    "z": 10,
    "hs": 0,
    "w": "constella.app",
    "k": "Actively hiring Marketing Intern AND Content Creator/Manager",
    "desc": "AI 'canvas' productivity tool"
  },
  {
    "n": "Demand Curve",
    "c": "San Francisco",
    "lat": 37.7749,
    "lng": -122.4194,
    "i": "EdTech/MarTech",
    "e": "10",
    "m": 22,
    "g": 10,
    "x": 11,
    "z": 9,
    "hs": 0,
    "w": "demandcurve.com",
    "k": "Newsletter 100,000+ subscribers; entire business is growth education",
    "desc": "Startup growth courses/newsletter/agency"
  },
  {
    "n": "Just Words (JustAI)",
    "c": "San Francisco",
    "lat": 37.7749,
    "lng": -122.4194,
    "i": "MarTech/AI",
    "e": "23",
    "m": 22,
    "g": 10,
    "x": 11,
    "z": 9,
    "hs": 0,
    "w": "getjust.ai",
    "k": "Customer logos incl. Coursera, ClickUp",
    "desc": "AI lifecycle-marketing automation platform"
  },
  {
    "n": "OneCrew",
    "c": "San Francisco",
    "lat": 37.7749,
    "lng": -122.4194,
    "i": "Business Software/SaaS",
    "e": null,
    "m": 15,
    "g": 14,
    "x": 15,
    "z": 8,
    "hs": 0,
    "w": "getonecrew.com",
    "k": "Product Marketing Lead role open",
    "desc": "B2B operations software"
  },
  {
    "n": "Pocket",
    "c": "San Francisco",
    "lat": 37.7749,
    "lng": -122.4194,
    "i": "Consumer/AI",
    "e": "15",
    "m": 18,
    "g": 14,
    "x": 11,
    "z": 9,
    "hs": 0,
    "w": "heypocket.com",
    "k": "No specific marketing signal found this pass -- check their site and socials before writing the email",
    "desc": "AI voice-recorder hardware/software"
  },
  {
    "n": "Uplane",
    "c": "San Francisco",
    "lat": 37.7749,
    "lng": -122.4194,
    "i": "MarTech/AI",
    "e": "22",
    "m": 22,
    "g": 10,
    "x": 11,
    "z": 9,
    "hs": 0,
    "w": "uplane.com",
    "k": "Marketing is the product itself -- high day-one relevance, but no confirmed opening; pitch a specific contribution",
    "desc": "AI replaces marketing agencies (ads/landing pages)"
  },
  {
    "n": "Zania",
    "c": "Palo Alto",
    "lat": 37.4419,
    "lng": -122.143,
    "i": "Business Software/AI",
    "e": null,
    "m": 12,
    "g": 9,
    "x": 11,
    "z": 8,
    "hs": 0,
    "w": "zania.ai",
    "k": "Active careers page, hiring Founding AE",
    "desc": "AI compliance/GRC agents (SOC2, HIPAA)"
  },
  {
    "n": "Koah",
    "c": "San Francisco",
    "lat": 37.7749,
    "lng": -122.4194,
    "i": "MarTech/AI",
    "e": null,
    "m": 22,
    "g": 10,
    "x": 11,
    "z": 8,
    "hs": 0,
    "w": "koahlabs.com",
    "k": "Client case studies (Liner, Bitly)",
    "desc": "AI-native ad-monetization/adtech platform"
  },
  {
    "n": "Talkable",
    "c": "San Francisco",
    "lat": 37.7749,
    "lng": -122.4194,
    "i": "MarTech/E-commerce",
    "e": "76",
    "m": 25,
    "g": 9,
    "x": 11,
    "z": 6,
    "hs": 0,
    "w": "talkable.com",
    "k": "Core product is referral/marketing tooling",
    "desc": "Referral-marketing platform for online stores"
  },
  {
    "n": "WisdomAI",
    "c": "San Mateo",
    "lat": 37.563,
    "lng": -122.3255,
    "i": "Business Software/AI",
    "e": null,
    "m": 12,
    "g": 10,
    "x": 15,
    "z": 8,
    "hs": 0,
    "w": "askwisdom.ai",
    "k": "No specific marketing signal found this pass -- check their site and socials before writing the email",
    "desc": "AI data-analyst SaaS for enterprise BI"
  },
  {
    "n": "daydream Labs",
    "c": "San Francisco",
    "lat": 37.7749,
    "lng": -122.4194,
    "i": "MarTech/AI",
    "e": null,
    "m": 22,
    "g": 10,
    "x": 11,
    "z": 8,
    "hs": 0,
    "w": "withdaydream.com",
    "k": "+178% MoM web traffic",
    "desc": "Programmatic SEO/GEO SaaS"
  },
  {
    "n": "AnswerThis",
    "c": "San Francisco",
    "lat": 37.7749,
    "lng": -122.4194,
    "i": "EdTech/AI",
    "e": "6",
    "m": 15,
    "g": 14,
    "x": 11,
    "z": 10,
    "hs": 0,
    "w": "answerthis.io",
    "k": "200,000+ researchers served; hiring sales; has a named CMO",
    "desc": "AI research/lit-review Q&A platform"
  },
  {
    "n": "LiquidMetal AI",
    "c": "Mountain View",
    "lat": 37.3861,
    "lng": -122.0839,
    "i": "DevTools/AI",
    "e": null,
    "m": 8,
    "g": 10,
    "x": 5,
    "z": 8,
    "hs": 0,
    "w": null,
    "k": "No specific marketing signal found this pass -- check their site and socials before writing the email",
    "desc": "Dev framework built for AI coding assistants"
  },
  {
    "n": "Aside",
    "c": "San Francisco",
    "lat": 37.7749,
    "lng": -122.4194,
    "i": "Consumer/AI",
    "e": "5",
    "m": 18,
    "g": 10,
    "x": 11,
    "z": 10,
    "hs": 0,
    "w": "aside.com",
    "k": "Team this small very likely has no dedicated marketer yet (unconfirmed) -- worth checking their site/socials directly",
    "desc": "AI browser that completes tasks across websites"
  },
  {
    "n": "Outset",
    "c": "San Francisco",
    "lat": 37.7749,
    "lng": -122.4194,
    "i": "MarTech/AI",
    "e": "30",
    "m": 22,
    "g": 8,
    "x": 11,
    "z": 8,
    "hs": 0,
    "w": "outset.ai",
    "k": "Marketing is the product itself -- high day-one relevance, but no confirmed opening; pitch a specific contribution",
    "desc": "AI-powered user interviews/market research"
  },
  {
    "n": "Shogun",
    "c": "San Francisco",
    "lat": 37.7749,
    "lng": -122.4194,
    "i": "E-commerce/MarTech",
    "e": "90",
    "m": 22,
    "g": 10,
    "x": 11,
    "z": 6,
    "hs": 0,
    "w": "getshogun.com",
    "k": "Marketing is the product itself -- high day-one relevance, but no confirmed opening; pitch a specific contribution",
    "desc": "Page-builder/CRO platform for Shopify/BigCommerce"
  },
  {
    "n": "Rampd",
    "c": "San Francisco",
    "lat": 37.7749,
    "lng": -122.4194,
    "i": "Business Software/Consulting",
    "e": null,
    "m": 15,
    "g": 10,
    "x": 15,
    "z": 8,
    "hs": 0,
    "w": "rampd.co",
    "k": "Founding roles for startup sales/marketing",
    "desc": "Boutique sales-team-building consultancy for startups"
  },
  {
    "n": "Risely AI",
    "c": "San Francisco",
    "lat": 37.7749,
    "lng": -122.4194,
    "i": "EdTech/AI",
    "e": "5",
    "m": 12,
    "g": 15,
    "x": 11,
    "z": 10,
    "hs": 0,
    "w": "risely.ai",
    "k": "Fast early growth",
    "desc": "AI agents automating university admin/retention"
  },
  {
    "n": "Anara",
    "c": "San Francisco",
    "lat": 37.7749,
    "lng": -122.4194,
    "i": "EdTech/AI",
    "e": "5",
    "m": 12,
    "g": 14,
    "x": 11,
    "z": 10,
    "hs": 0,
    "w": "anara.com",
    "k": "Team this small very likely has no dedicated marketer yet (unconfirmed) -- worth checking their site/socials directly",
    "desc": "AI for scientific research documents"
  },
  {
    "n": "Apten",
    "c": "San Francisco",
    "lat": 37.7749,
    "lng": -122.4194,
    "i": "SalesTech/AI",
    "e": "6",
    "m": 12,
    "g": 14,
    "x": 11,
    "z": 10,
    "hs": 0,
    "w": "apten.ai",
    "k": "Team this small very likely has no dedicated marketer yet (unconfirmed) -- worth checking their site/socials directly",
    "desc": "Omnichannel AI sales agents (SMS/voice/email)"
  },
  {
    "n": "Astor",
    "c": "San Francisco",
    "lat": 37.7749,
    "lng": -122.4194,
    "i": "Fintech/AI",
    "e": "5",
    "m": 12,
    "g": 14,
    "x": 11,
    "z": 10,
    "hs": 0,
    "w": "astor.app",
    "k": "Team this small very likely has no dedicated marketer yet (unconfirmed) -- worth checking their site/socials directly",
    "desc": "AI investment advisor for retail investors"
  },
  {
    "n": "Callbook AI",
    "c": "San Francisco",
    "lat": 37.7749,
    "lng": -122.4194,
    "i": "Fintech/AI",
    "e": "7",
    "m": 12,
    "g": 14,
    "x": 11,
    "z": 10,
    "hs": 0,
    "w": "callbook.ai",
    "k": "Team this small very likely has no dedicated marketer yet (unconfirmed) -- worth checking their site/socials directly",
    "desc": "AI collections agency for debt portfolios"
  },
  {
    "n": "Casey",
    "c": "San Francisco",
    "lat": 37.7749,
    "lng": -122.4194,
    "i": "Fintech/AI",
    "e": "5",
    "m": 12,
    "g": 14,
    "x": 11,
    "z": 10,
    "hs": 0,
    "w": "caseyinsure.com",
    "k": "Team this small very likely has no dedicated marketer yet (unconfirmed) -- worth checking their site/socials directly",
    "desc": "AI-native commercial insurance brokerage"
  },
  {
    "n": "Checkbook",
    "c": "San Mateo",
    "lat": 37.563,
    "lng": -122.3255,
    "i": "Fintech",
    "e": null,
    "m": 12,
    "g": 10,
    "x": 11,
    "z": 8,
    "hs": 0,
    "w": "checkbook.io",
    "k": "Internship Talent Pool listing open",
    "desc": "Digital payments/checks API"
  },
  {
    "n": "Circleback",
    "c": "San Francisco",
    "lat": 37.7749,
    "lng": -122.4194,
    "i": "Productivity/AI",
    "e": "8",
    "m": 12,
    "g": 14,
    "x": 11,
    "z": 10,
    "hs": 0,
    "w": "circleback.ai",
    "k": "Team this small very likely has no dedicated marketer yet (unconfirmed) -- worth checking their site/socials directly",
    "desc": "AI meeting notes/action items"
  },
  {
    "n": "Cognichip",
    "c": "Redwood City",
    "lat": 37.4852,
    "lng": -122.2364,
    "i": "DeepTech/AI",
    "e": "75",
    "m": 8,
    "g": 10,
    "x": 11,
    "z": 6,
    "hs": 0,
    "w": "cognichip.ai",
    "k": "No specific marketing signal found this pass -- check their site and socials before writing the email",
    "desc": "AI foundation models for semiconductor chip design"
  },
  {
    "n": "Curtsy",
    "c": "San Francisco",
    "lat": 37.7749,
    "lng": -122.4194,
    "i": "E-commerce/Consumer",
    "e": "15",
    "m": 18,
    "g": 9,
    "x": 11,
    "z": 9,
    "hs": 0,
    "w": "curtsyapp.com",
    "k": "No specific marketing signal found this pass -- check their site and socials before writing the email",
    "desc": "Mobile resale marketplace for women's clothing"
  },
  {
    "n": "Dench.com",
    "c": "San Francisco",
    "lat": 37.7749,
    "lng": -122.4194,
    "i": "Business Software/AI",
    "e": "6",
    "m": 12,
    "g": 14,
    "x": 11,
    "z": 10,
    "hs": 0,
    "w": "dench.com",
    "k": "Team this small very likely has no dedicated marketer yet (unconfirmed) -- worth checking their site/socials directly",
    "desc": "AI CRM with embedded agent deployment"
  },
  {
    "n": "Excellence Learning",
    "c": "San Francisco",
    "lat": 37.7749,
    "lng": -122.4194,
    "i": "EdTech/AI",
    "e": "4",
    "m": 12,
    "g": 14,
    "x": 11,
    "z": 10,
    "hs": 0,
    "w": "excellence-ai.com",
    "k": "Team this small very likely has no dedicated marketer yet (unconfirmed) -- worth checking their site/socials directly",
    "desc": "AI math/science tutor (Kumon alternative)"
  },
  {
    "n": "HEVN",
    "c": "San Francisco",
    "lat": 37.7749,
    "lng": -122.4194,
    "i": "Fintech",
    "e": "8",
    "m": 12,
    "g": 14,
    "x": 11,
    "z": 10,
    "hs": 0,
    "w": "gethevn.com",
    "k": "Team this small very likely has no dedicated marketer yet (unconfirmed) -- worth checking their site/socials directly",
    "desc": "Cross-border B2B payments for exporters"
  },
  {
    "n": "Hypotenuse AI",
    "c": "San Francisco",
    "lat": 37.7749,
    "lng": -122.4194,
    "i": "E-commerce/AI",
    "e": "15",
    "m": 18,
    "g": 9,
    "x": 11,
    "z": 9,
    "hs": 0,
    "w": "hypotenuse.ai",
    "k": "No specific marketing signal found this pass -- check their site and socials before writing the email",
    "desc": "AI product-content/data enrichment platform"
  },
  {
    "n": "Kinro",
    "c": "San Francisco",
    "lat": 37.7749,
    "lng": -122.4194,
    "i": "Fintech/AI",
    "e": "6",
    "m": 12,
    "g": 14,
    "x": 11,
    "z": 10,
    "hs": 0,
    "w": "kinro.com",
    "k": "Team this small very likely has no dedicated marketer yet (unconfirmed) -- worth checking their site/socials directly",
    "desc": "AI agents automate SMB insurance brokerage"
  },
  {
    "n": "Magnetic",
    "c": "San Francisco",
    "lat": 37.7749,
    "lng": -122.4194,
    "i": "Business Software/AI",
    "e": "10",
    "m": 12,
    "g": 15,
    "x": 11,
    "z": 9,
    "hs": 0,
    "w": "magnetictax.com",
    "k": "Actively hiring sales/eng/ops",
    "desc": "AI tax preparer for CPA firms"
  },
  {
    "n": "Mendaera",
    "c": "San Mateo",
    "lat": 37.563,
    "lng": -122.3255,
    "i": "MedTech/AI",
    "e": null,
    "m": 10,
    "g": 8,
    "x": 15,
    "z": 8,
    "hs": 0,
    "w": "mendaera.com",
    "k": "Director of Commercial Marketing role open",
    "desc": "Robotic/AI medical devices"
  },
  {
    "n": "Prox",
    "c": "San Francisco",
    "lat": 37.7749,
    "lng": -122.4194,
    "i": "Business Software/AI",
    "e": "7",
    "m": 12,
    "g": 14,
    "x": 11,
    "z": 10,
    "hs": 0,
    "w": "useprox.com",
    "k": "Team this small very likely has no dedicated marketer yet (unconfirmed) -- worth checking their site/socials directly",
    "desc": "Multimodal AI technical-support agent"
  },
  {
    "n": "Tesora",
    "c": "San Francisco",
    "lat": 37.7749,
    "lng": -122.4194,
    "i": "Fintech/AI",
    "e": "5",
    "m": 12,
    "g": 14,
    "x": 11,
    "z": 10,
    "hs": 0,
    "w": "tesora.ai",
    "k": "Team this small very likely has no dedicated marketer yet (unconfirmed) -- worth checking their site/socials directly",
    "desc": "AI agents for P&C insurance actuaries"
  },
  {
    "n": "The Essential",
    "c": "San Francisco",
    "lat": 37.7749,
    "lng": -122.4194,
    "i": "E-commerce/Consumer",
    "e": "11",
    "m": 18,
    "g": 9,
    "x": 11,
    "z": 9,
    "hs": 0,
    "w": "theessential.com",
    "k": "Team this small very likely has no dedicated marketer yet (unconfirmed) -- worth checking their site/socials directly",
    "desc": "Members-only curated essentials brand"
  },
  {
    "n": "Veritus",
    "c": "San Francisco",
    "lat": 37.7749,
    "lng": -122.4194,
    "i": "Fintech/AI",
    "e": "10",
    "m": 12,
    "g": 15,
    "x": 11,
    "z": 9,
    "hs": 0,
    "w": "veritus.com",
    "k": "Actively hiring incl. Founding AE",
    "desc": "AI agents for loan servicing/collections"
  },
  {
    "n": "Freya",
    "c": "San Francisco",
    "lat": 37.7749,
    "lng": -122.4194,
    "i": "Fintech/AI",
    "e": "14",
    "m": 12,
    "g": 14,
    "x": 11,
    "z": 9,
    "hs": 0,
    "w": "freyavoice.ai",
    "k": "Team this small very likely has no dedicated marketer yet (unconfirmed) -- worth checking their site/socials directly",
    "desc": "Voice AI for banking/financial services"
  },
  {
    "n": "Gemnote",
    "c": "San Francisco",
    "lat": 37.7749,
    "lng": -122.4194,
    "i": "E-commerce/B2B",
    "e": "40",
    "m": 18,
    "g": 9,
    "x": 11,
    "z": 8,
    "hs": 0,
    "w": "gemnote.com",
    "k": "No specific marketing signal found this pass -- check their site and socials before writing the email",
    "desc": "Custom/branded merchandise & corporate swag platform"
  },
  {
    "n": "Lexi",
    "c": "San Francisco",
    "lat": 37.7749,
    "lng": -122.4194,
    "i": "Business Software/AI",
    "e": "15",
    "m": 12,
    "g": 14,
    "x": 11,
    "z": 9,
    "hs": 0,
    "w": "getlexi.io",
    "k": "No specific marketing signal found this pass -- check their site and socials before writing the email",
    "desc": "AI operating system for legal teams"
  },
  {
    "n": "Proven Group (Proven Skincare)",
    "c": "San Francisco",
    "lat": 37.7749,
    "lng": -122.4194,
    "i": "E-commerce/Consumer",
    "e": "40",
    "m": 18,
    "g": 9,
    "x": 11,
    "z": 8,
    "hs": 0,
    "w": "provenskincare.com",
    "k": "No specific marketing signal found this pass -- check their site and socials before writing the email",
    "desc": "Personalized DTC skincare brand"
  },
  {
    "n": "Semble",
    "c": "San Francisco",
    "lat": 37.7749,
    "lng": -122.4194,
    "i": "Business Software/AI",
    "e": "14",
    "m": 12,
    "g": 14,
    "x": 11,
    "z": 9,
    "hs": 0,
    "w": "sembleai.com",
    "k": "Team this small very likely has no dedicated marketer yet (unconfirmed) -- worth checking their site/socials directly",
    "desc": "AI workflow OS for construction/integrator businesses"
  },
  {
    "n": "14.ai",
    "c": "San Francisco",
    "lat": 37.7749,
    "lng": -122.4194,
    "i": "Business Software/AI",
    "e": null,
    "m": 12,
    "g": 14,
    "x": 11,
    "z": 8,
    "hs": 0,
    "w": "14.ai",
    "k": "No specific marketing signal found this pass -- check their site and socials before writing the email",
    "desc": "AI-native customer support for B2C brands"
  },
  {
    "n": "Corvera.ai",
    "c": "San Francisco",
    "lat": 37.7749,
    "lng": -122.4194,
    "i": "Business Software/AI",
    "e": null,
    "m": 12,
    "g": 14,
    "x": 11,
    "z": 8,
    "hs": 0,
    "w": "corvera.ai",
    "k": "No specific marketing signal found this pass -- check their site and socials before writing the email",
    "desc": "Autonomous ops layer for CPG supply chain"
  },
  {
    "n": "Diligence Squared",
    "c": "San Francisco",
    "lat": 37.7749,
    "lng": -122.4194,
    "i": "Fintech/AI",
    "e": null,
    "m": 12,
    "g": 14,
    "x": 11,
    "z": 8,
    "hs": 0,
    "w": "diligencesquared.com",
    "k": "No specific marketing signal found this pass -- check their site and socials before writing the email",
    "desc": "AI platform turning expert interviews into investment insights"
  },
  {
    "n": "Firecrawl",
    "c": "San Francisco",
    "lat": 37.7749,
    "lng": -122.4194,
    "i": "DevTools/AI",
    "e": "30",
    "m": 10,
    "g": 12,
    "x": 15,
    "z": 8,
    "hs": 0,
    "w": "firecrawl.dev",
    "k": "Head of Growth Marketing role open",
    "desc": "Web data/scraping API for AI agents"
  },
  {
    "n": "Herd Security",
    "c": "San Francisco",
    "lat": 37.7749,
    "lng": -122.4194,
    "i": "Business Software/AI",
    "e": null,
    "m": 12,
    "g": 14,
    "x": 11,
    "z": 8,
    "hs": 0,
    "w": "herdsecurity.io",
    "k": "No specific marketing signal found this pass -- check their site and socials before writing the email",
    "desc": "AI security-awareness training/GRC platform"
  },
  {
    "n": "Joy",
    "c": "San Francisco",
    "lat": 37.7749,
    "lng": -122.4194,
    "i": "E-commerce/Consumer",
    "e": "100",
    "m": 18,
    "g": 10,
    "x": 11,
    "z": 6,
    "hs": 0,
    "w": "withjoy.com",
    "k": "No specific marketing signal found this pass -- check their site and socials before writing the email",
    "desc": "Life-events planning platform with retail"
  },
  {
    "n": "Kalinda",
    "c": "San Francisco",
    "lat": 37.7749,
    "lng": -122.4194,
    "i": "Insurtech/AI",
    "e": null,
    "m": 12,
    "g": 14,
    "x": 11,
    "z": 8,
    "hs": 0,
    "w": "kalinda.ai",
    "k": "No specific marketing signal found this pass -- check their site and socials before writing the email",
    "desc": "AI extraction/summarization of claimant medical records"
  },
  {
    "n": "TriFetch",
    "c": "San Francisco",
    "lat": 37.7749,
    "lng": -122.4194,
    "i": "Business Software/AI",
    "e": null,
    "m": 12,
    "g": 14,
    "x": 11,
    "z": 8,
    "hs": 0,
    "w": "trifetch.ai",
    "k": "No specific marketing signal found this pass -- check their site and socials before writing the email",
    "desc": "Healthcare AI automation (referrals, patient comms)"
  },
  {
    "n": "forml",
    "c": "San Francisco",
    "lat": 37.7749,
    "lng": -122.4194,
    "i": "Business Software/AI",
    "e": null,
    "m": 12,
    "g": 14,
    "x": 11,
    "z": 8,
    "hs": 0,
    "w": "forml.ai",
    "k": "No specific marketing signal found this pass -- check their site and socials before writing the email",
    "desc": "Document intelligence/enterprise ML automation SaaS"
  },
  {
    "n": "BIK",
    "c": "San Francisco",
    "lat": 37.7749,
    "lng": -122.4194,
    "i": "E-commerce/AI",
    "e": "55",
    "m": 18,
    "g": 9,
    "x": 11,
    "z": 6,
    "hs": 0,
    "w": "bik.ai",
    "k": "No specific marketing signal found this pass -- check their site and socials before writing the email",
    "desc": "Agentic AI CRM/commerce automation for brands"
  },
  {
    "n": "Hyperspell",
    "c": "San Francisco",
    "lat": 37.7749,
    "lng": -122.4194,
    "i": "DevTools/AI",
    "e": "8",
    "m": 8,
    "g": 15,
    "x": 11,
    "z": 10,
    "hs": 0,
    "w": "hyperspell.com",
    "k": "Actively hiring eng roles",
    "desc": "Memory/context layer for AI agents (Slack/Gmail/Notion)"
  },
  {
    "n": "Network Right",
    "c": "San Francisco",
    "lat": 37.7749,
    "lng": -122.4194,
    "i": "Business Software/IT",
    "e": null,
    "m": 15,
    "g": 10,
    "x": 11,
    "z": 8,
    "hs": 0,
    "w": "networkright.com",
    "k": "Founding Marketing Lead role open",
    "desc": "IT/security managed services"
  },
  {
    "n": "BetterBasket",
    "c": "San Francisco",
    "lat": 37.7749,
    "lng": -122.4194,
    "i": "Retail/AI",
    "e": "5",
    "m": 8,
    "g": 14,
    "x": 11,
    "z": 10,
    "hs": 0,
    "w": "betterbasket.com",
    "k": "Team this small very likely has no dedicated marketer yet (unconfirmed) -- worth checking their site/socials directly",
    "desc": "AI pricing/promotion optimization for grocers"
  },
  {
    "n": "Endor Labs",
    "c": "Palo Alto",
    "lat": 37.4419,
    "lng": -122.143,
    "i": "Security/AI",
    "e": "125",
    "m": 10,
    "g": 6,
    "x": 11,
    "z": 4,
    "hs": 0,
    "w": "endorlabs.com",
    "k": "Growth Marketing Manager role open",
    "desc": "AI code/open-source security scanning"
  },
  {
    "n": "HyperProbe",
    "c": "San Francisco",
    "lat": 37.7749,
    "lng": -122.4194,
    "i": "DevTools/AI",
    "e": "8",
    "m": 8,
    "g": 14,
    "x": 11,
    "z": 10,
    "hs": 0,
    "w": "hyperprobe.co",
    "k": "Team this small very likely has no dedicated marketer yet (unconfirmed) -- worth checking their site/socials directly",
    "desc": "Runtime monitoring for AI agent apps"
  },
  {
    "n": "IPMD Inc (EchoAI)",
    "c": "San Mateo",
    "lat": 37.563,
    "lng": -122.3255,
    "i": "HealthTech/AI",
    "e": "30",
    "m": 8,
    "g": 10,
    "x": 11,
    "z": 8,
    "hs": 0,
    "w": "ipmdinc.com",
    "k": "Dedicated Internship Program nav link",
    "desc": "Emotional AI/telemedicine mental-health tech"
  },
  {
    "n": "Luminal",
    "c": "San Francisco",
    "lat": 37.7749,
    "lng": -122.4194,
    "i": "AI/DevTools",
    "e": "7",
    "m": 8,
    "g": 14,
    "x": 11,
    "z": 10,
    "hs": 0,
    "w": "luminalai.com",
    "k": "Team this small very likely has no dedicated marketer yet (unconfirmed) -- worth checking their site/socials directly",
    "desc": "ML compiler/inference infra"
  },
  {
    "n": "Macroscope",
    "c": "San Francisco",
    "lat": 37.7749,
    "lng": -122.4194,
    "i": "DevTools/AI",
    "e": "30",
    "m": 8,
    "g": 12,
    "x": 15,
    "z": 8,
    "hs": 0,
    "w": "macroscope.com",
    "k": "Growth/Demand Gen Marketer role open",
    "desc": "AI codebase-understanding tool"
  },
  {
    "n": "Moss",
    "c": "San Francisco",
    "lat": 37.7749,
    "lng": -122.4194,
    "i": "DevTools/AI",
    "e": "5",
    "m": 8,
    "g": 14,
    "x": 11,
    "z": 10,
    "hs": 0,
    "w": "moss.dev",
    "k": "Team this small very likely has no dedicated marketer yet (unconfirmed) -- worth checking their site/socials directly",
    "desc": "Semantic search infra for voice agents"
  },
  {
    "n": "Patent Watch",
    "c": "San Francisco",
    "lat": 37.7749,
    "lng": -122.4194,
    "i": "Legal Tech/AI",
    "e": "6",
    "m": 8,
    "g": 14,
    "x": 11,
    "z": 10,
    "hs": 0,
    "w": "patentwatch.ai",
    "k": "Team this small very likely has no dedicated marketer yet (unconfirmed) -- worth checking their site/socials directly",
    "desc": "AI patent-infringement detection"
  },
  {
    "n": "Educato",
    "c": "San Francisco",
    "lat": 37.7749,
    "lng": -122.4194,
    "i": "EdTech/AI",
    "e": "5",
    "m": 12,
    "g": 9,
    "x": 11,
    "z": 10,
    "hs": 0,
    "w": "educato.com",
    "k": "Team this small very likely has no dedicated marketer yet (unconfirmed) -- worth checking their site/socials directly",
    "desc": "AI-generated worldwide exam-prep content"
  },
  {
    "n": "Finvest",
    "c": "San Francisco",
    "lat": 37.7749,
    "lng": -122.4194,
    "i": "Fintech/AI",
    "e": "5",
    "m": 12,
    "g": 9,
    "x": 11,
    "z": 10,
    "hs": 0,
    "w": "getfinvest.com",
    "k": "Team this small very likely has no dedicated marketer yet (unconfirmed) -- worth checking their site/socials directly",
    "desc": "AI wealth manager for mass-affluent households"
  },
  {
    "n": "Mathos",
    "c": "San Francisco",
    "lat": 37.7749,
    "lng": -122.4194,
    "i": "EdTech/AI",
    "e": "5",
    "m": 12,
    "g": 9,
    "x": 11,
    "z": 10,
    "hs": 0,
    "w": "info.mathos.ai",
    "k": "Team this small very likely has no dedicated marketer yet (unconfirmed) -- worth checking their site/socials directly",
    "desc": "AI math problem-solver/tutor"
  },
  {
    "n": "Dealpath",
    "c": "San Francisco",
    "lat": 37.7749,
    "lng": -122.4194,
    "i": "Business Software/SaaS",
    "e": "30",
    "m": 12,
    "g": 10,
    "x": 11,
    "z": 8,
    "hs": 0,
    "w": "dealpath.com",
    "k": "Senior Revenue Operations Manager role open",
    "desc": "Real-estate investment management SaaS"
  },
  {
    "n": "Ello",
    "c": "San Francisco",
    "lat": 37.7749,
    "lng": -122.4194,
    "i": "EdTech/AI",
    "e": "45",
    "m": 12,
    "g": 10,
    "x": 11,
    "z": 8,
    "hs": 0,
    "w": "ello.com",
    "k": "No specific marketing signal found this pass -- check their site and socials before writing the email",
    "desc": "AI 1:1 reading coach for children"
  },
  {
    "n": "Fazeshift",
    "c": "San Francisco",
    "lat": 37.7749,
    "lng": -122.4194,
    "i": "Fintech/AI",
    "e": null,
    "m": 12,
    "g": 10,
    "x": 11,
    "z": 8,
    "hs": 0,
    "w": "fazeshift.com",
    "k": "'Women Founded' recognition",
    "desc": "AI accounts-receivable automation SaaS"
  },
  {
    "n": "Firework",
    "c": "San Mateo",
    "lat": 37.563,
    "lng": -122.3255,
    "i": "MarTech/AI",
    "e": "270",
    "m": 22,
    "g": 4,
    "x": 5,
    "z": 4,
    "hs": 0,
    "w": "firework.com",
    "k": "Historically posted Product Ops Intern open to sophomores+; AI Content Intern role posted",
    "desc": "AI/video-commerce marketing tech"
  },
  {
    "n": "Keeper",
    "c": "San Francisco",
    "lat": 37.7749,
    "lng": -122.4194,
    "i": "Fintech/AI",
    "e": "16",
    "m": 12,
    "g": 9,
    "x": 11,
    "z": 9,
    "hs": 0,
    "w": "keepertax.com",
    "k": "No specific marketing signal found this pass -- check their site and socials before writing the email",
    "desc": "AI tax filing for complex returns"
  },
  {
    "n": "Koala (Teach with Koala)",
    "c": "San Francisco",
    "lat": 37.7749,
    "lng": -122.4194,
    "i": "EdTech",
    "e": "11",
    "m": 12,
    "g": 9,
    "x": 11,
    "z": 9,
    "hs": 0,
    "w": "teachwithkoala.com",
    "k": "Team this small very likely has no dedicated marketer yet (unconfirmed) -- worth checking their site/socials directly",
    "desc": "Game-inspired interactive online teaching platform"
  },
  {
    "n": "Modern Relay",
    "c": "San Francisco",
    "lat": 37.7749,
    "lng": -122.4194,
    "i": "DevTools/AI",
    "e": null,
    "m": 8,
    "g": 14,
    "x": 11,
    "z": 8,
    "hs": 0,
    "w": "modernrelay.com",
    "k": "No specific marketing signal found this pass -- check their site and socials before writing the email",
    "desc": "Context-graph data infra for enterprise AI agents"
  },
  {
    "n": "NEXGENT",
    "c": "San Francisco",
    "lat": 37.7749,
    "lng": -122.4194,
    "i": "EdTech",
    "e": "25",
    "m": 12,
    "g": 9,
    "x": 11,
    "z": 9,
    "hs": 0,
    "w": "ngt.academy",
    "k": "No specific marketing signal found this pass -- check their site and socials before writing the email",
    "desc": "Job-ready IT networking training/certification"
  },
  {
    "n": "NationGraph",
    "c": "San Francisco",
    "lat": 37.7749,
    "lng": -122.4194,
    "i": "Business Software/AI",
    "e": null,
    "m": 12,
    "g": 10,
    "x": 11,
    "z": 8,
    "hs": 0,
    "w": "nationgraph.com",
    "k": "No specific marketing signal found this pass -- check their site and socials before writing the email",
    "desc": "AI intelligence platform for public-sector contracts"
  },
  {
    "n": "Phonely",
    "c": "San Francisco",
    "lat": 37.7749,
    "lng": -122.4194,
    "i": "Business Software/AI",
    "e": null,
    "m": 12,
    "g": 10,
    "x": 11,
    "z": 8,
    "hs": 0,
    "w": "phonely.ai",
    "k": "No specific marketing signal found this pass -- check their site and socials before writing the email",
    "desc": "AI voice platform automating business phone calls"
  },
  {
    "n": "Prime Intellect",
    "c": "San Francisco",
    "lat": 37.7749,
    "lng": -122.4194,
    "i": "AI/Infra",
    "e": "30",
    "m": 10,
    "g": 12,
    "x": 11,
    "z": 8,
    "hs": 0,
    "w": "primeintellect.ai",
    "k": "Head of Marketing AND Head of Growth roles open",
    "desc": "AI compute/agents infrastructure"
  },
  {
    "n": "San Francisco Compute Company",
    "c": "San Francisco",
    "lat": 37.7749,
    "lng": -122.4194,
    "i": "AI/Infra",
    "e": "29",
    "m": 8,
    "g": 10,
    "x": 15,
    "z": 8,
    "hs": 0,
    "w": "sfcompute.com",
    "k": "Chief of Staff to CEO role open",
    "desc": "GPU compute marketplace"
  },
  {
    "n": "Sazabi",
    "c": "San Francisco",
    "lat": 37.7749,
    "lng": -122.4194,
    "i": "DevTools/AI",
    "e": null,
    "m": 8,
    "g": 14,
    "x": 11,
    "z": 8,
    "hs": 0,
    "w": "sazabi.com",
    "k": "No specific marketing signal found this pass -- check their site and socials before writing the email",
    "desc": "AI-native observability platform for engineers"
  },
  {
    "n": "SuperPlane",
    "c": "San Francisco",
    "lat": 37.7749,
    "lng": -122.4194,
    "i": "DevTools/AI",
    "e": null,
    "m": 8,
    "g": 14,
    "x": 11,
    "z": 8,
    "hs": 0,
    "w": "superplane.com",
    "k": "No specific marketing signal found this pass -- check their site and socials before writing the email",
    "desc": "AI-first DevOps/platform-engineering control plane"
  },
  {
    "n": "Traceroot",
    "c": "San Francisco",
    "lat": 37.7749,
    "lng": -122.4194,
    "i": "DevTools/AI",
    "e": null,
    "m": 8,
    "g": 14,
    "x": 11,
    "z": 8,
    "hs": 0,
    "w": "traceroot.ai",
    "k": "No specific marketing signal found this pass -- check their site and socials before writing the email",
    "desc": "AI devtool auto-diagnosing production bugs"
  },
  {
    "n": "t54 Labs",
    "c": "San Francisco",
    "lat": 37.7749,
    "lng": -122.4194,
    "i": "Fintech/DevTools",
    "e": null,
    "m": 8,
    "g": 14,
    "x": 11,
    "z": 8,
    "hs": 0,
    "w": "t54.ai",
    "k": "No specific marketing signal found this pass -- check their site and socials before writing the email",
    "desc": "Trust/compliance infra for AI-agent financial transactions"
  },
  {
    "n": "Acely",
    "c": "San Francisco",
    "lat": 37.7749,
    "lng": -122.4194,
    "i": "EdTech/AI",
    "e": "30",
    "m": 12,
    "g": 9,
    "x": 11,
    "z": 8,
    "hs": 0,
    "w": "acely.com",
    "k": "No specific marketing signal found this pass -- check their site and socials before writing the email",
    "desc": "AI SAT/ACT coach for high schoolers"
  },
  {
    "n": "Two Dots",
    "c": "San Francisco",
    "lat": 37.7749,
    "lng": -122.4194,
    "i": "Fintech/AI",
    "e": "28",
    "m": 12,
    "g": 9,
    "x": 11,
    "z": 8,
    "hs": 0,
    "w": "twodots.com",
    "k": "No specific marketing signal found this pass -- check their site and socials before writing the email",
    "desc": "AI fraud prevention/income verification for lenders"
  },
  {
    "n": "Coval",
    "c": "San Francisco",
    "lat": 37.7749,
    "lng": -122.4194,
    "i": "DevTools/AI",
    "e": null,
    "m": 8,
    "g": 12,
    "x": 11,
    "z": 8,
    "hs": 0,
    "w": "coval.ai",
    "k": "Has open Head of Growth role",
    "desc": "Simulation/evaluation platform for AI agents"
  },
  {
    "n": "Illoca",
    "c": "San Francisco",
    "lat": 37.7749,
    "lng": -122.4194,
    "i": "Business Software/AI",
    "e": "75",
    "m": 12,
    "g": 10,
    "x": 11,
    "z": 6,
    "hs": 0,
    "w": "illoca.com",
    "k": "No specific marketing signal found this pass -- check their site and socials before writing the email",
    "desc": "Generative-AI design canvas for architecture"
  },
  {
    "n": "Onyx",
    "c": "San Francisco",
    "lat": 37.7749,
    "lng": -122.4194,
    "i": "DevTools/AI",
    "e": "20",
    "m": 8,
    "g": 10,
    "x": 11,
    "z": 9,
    "hs": 0,
    "w": "onyx.app",
    "k": "No specific marketing signal found this pass -- check their site and socials before writing the email",
    "desc": "Open-source AI chat UI over company knowledge"
  },
  {
    "n": "Deep Cogito",
    "c": "San Francisco",
    "lat": 37.7749,
    "lng": -122.4194,
    "i": "AI/Infra",
    "e": null,
    "m": 8,
    "g": 10,
    "x": 11,
    "z": 8,
    "hs": 0,
    "w": "deepcogito.com",
    "k": "No specific marketing signal found this pass -- check their site and socials before writing the email",
    "desc": "AI reasoning language models"
  },
  {
    "n": "Featherless.ai",
    "c": "San Francisco",
    "lat": 37.7749,
    "lng": -122.4194,
    "i": "DevTools/AI",
    "e": "75",
    "m": 8,
    "g": 12,
    "x": 11,
    "z": 6,
    "hs": 0,
    "w": "featherless.ai",
    "k": "97.7K monthly visits, +133% growth",
    "desc": "Serverless AI hosting/inference platform"
  },
  {
    "n": "Nova Intelligence",
    "c": "San Francisco",
    "lat": 37.7749,
    "lng": -122.4194,
    "i": "DevTools/AI",
    "e": null,
    "m": 8,
    "g": 10,
    "x": 11,
    "z": 8,
    "hs": 0,
    "w": "novaintelligence.com",
    "k": "No specific marketing signal found this pass -- check their site and socials before writing the email",
    "desc": "AI dev platform for SAP developers"
  },
  {
    "n": "Standard Intelligence",
    "c": "San Francisco",
    "lat": 37.7749,
    "lng": -122.4194,
    "i": "AI/Infra",
    "e": null,
    "m": 8,
    "g": 10,
    "x": 11,
    "z": 8,
    "hs": 0,
    "w": "si.inc",
    "k": "No specific marketing signal found this pass -- check their site and socials before writing the email",
    "desc": "AI research co. building computer-use models"
  },
  {
    "n": "Zinc",
    "c": "San Francisco",
    "lat": 37.7749,
    "lng": -122.4194,
    "i": "E-commerce/DevTools",
    "e": "10",
    "m": 8,
    "g": 9,
    "x": 11,
    "z": 9,
    "hs": 0,
    "w": "zinc.com",
    "k": "Team this small very likely has no dedicated marketer yet (unconfirmed) -- worth checking their site/socials directly",
    "desc": "Programmable commerce/purchasing API layer"
  },
  {
    "n": "AfterQuery",
    "c": "San Francisco",
    "lat": 37.7749,
    "lng": -122.4194,
    "i": "AI/Infra",
    "e": "75",
    "m": 8,
    "g": 10,
    "x": 11,
    "z": 6,
    "hs": 0,
    "w": "afterquery.com",
    "k": "No specific marketing signal found this pass -- check their site and socials before writing the email",
    "desc": "AI expert-dataset company (training data)"
  },
  {
    "n": "HockeyStack",
    "c": "San Francisco",
    "lat": 37.7749,
    "lng": -122.4194,
    "i": "MarTech/SaaS",
    "e": "65",
    "m": 8,
    "g": 10,
    "x": 11,
    "z": 6,
    "hs": 0,
    "w": "hockeystack.com",
    "k": "Active YC page, funding press",
    "desc": "B2B revenue intelligence/marketing analytics SaaS"
  },
  {
    "n": "Infisical",
    "c": "San Francisco",
    "lat": 37.7749,
    "lng": -122.4194,
    "i": "DevTools/Security",
    "e": "30",
    "m": 10,
    "g": 12,
    "x": 5,
    "z": 8,
    "hs": 0,
    "w": "infisical.com",
    "k": "Growth Marketing Manager role open",
    "desc": "Secrets/identity/access management SaaS"
  },
  {
    "n": "Patlytics",
    "c": "San Francisco",
    "lat": 37.7749,
    "lng": -122.4194,
    "i": "Legal Tech/AI",
    "e": null,
    "m": 8,
    "g": 8,
    "x": 11,
    "z": 8,
    "hs": 0,
    "w": "patlytics.ai",
    "k": "No specific marketing signal found this pass -- check their site and socials before writing the email",
    "desc": "AI patent-intelligence SaaS"
  },
  {
    "n": "QuiverAI",
    "c": "San Francisco",
    "lat": 37.7749,
    "lng": -122.4194,
    "i": "Design/SaaS",
    "e": "75",
    "m": 8,
    "g": 10,
    "x": 11,
    "z": 6,
    "hs": 0,
    "w": "quiver.ai",
    "k": "No specific marketing signal found this pass -- check their site and socials before writing the email",
    "desc": "AI vector-graphics generation/editing"
  },
  {
    "n": "Rork",
    "c": "San Francisco",
    "lat": 37.7749,
    "lng": -122.4194,
    "i": "DevTools/AI",
    "e": "75",
    "m": 8,
    "g": 10,
    "x": 11,
    "z": 6,
    "hs": 0,
    "w": "rork.com",
    "k": "1.25M monthly visits",
    "desc": "AI no-code mobile-app builder"
  },
  {
    "n": "Snackpass",
    "c": "San Francisco",
    "lat": 37.7749,
    "lng": -122.4194,
    "i": "Consumer/E-commerce",
    "e": "38",
    "m": 8,
    "g": 8,
    "x": 11,
    "z": 8,
    "hs": 0,
    "w": "snackpass.co",
    "k": "No specific marketing signal found this pass -- check their site and socials before writing the email",
    "desc": "Social food-ordering app with rewards"
  },
  {
    "n": "Mintlify",
    "c": "San Francisco",
    "lat": 37.7749,
    "lng": -122.4194,
    "i": "DevTools/AI",
    "e": "75",
    "m": 8,
    "g": 8,
    "x": 11,
    "z": 6,
    "hs": 0,
    "w": "mintlify.com",
    "k": "388K monthly visits; acquired Helicone & Trieve",
    "desc": "AI-powered developer documentation platform"
  },
  {
    "n": "OpusClip",
    "c": "San Francisco",
    "lat": 37.7749,
    "lng": -122.4194,
    "i": "Consumer/AI",
    "e": "125",
    "m": 18,
    "g": 6,
    "x": 5,
    "z": 4,
    "hs": 0,
    "w": "opus.pro",
    "k": "Social Growth Intern role explicitly open",
    "desc": "AI short-form video clipping tool"
  },
  {
    "n": "Bobyard",
    "c": "San Francisco",
    "lat": 37.7749,
    "lng": -122.4194,
    "i": "Business Software/AI",
    "e": "125",
    "m": 15,
    "g": 4,
    "x": 5,
    "z": 4,
    "hs": 0,
    "w": "bobyard.com",
    "k": "3 open ops roles + Social Media Manager",
    "desc": "AI construction-estimating software"
  },
  {
    "n": "Numeral",
    "c": "San Francisco",
    "lat": 37.7749,
    "lng": -122.4194,
    "i": "Fintech/SaaS",
    "e": "125",
    "m": 10,
    "g": 4,
    "x": 5,
    "z": 4,
    "hs": 0,
    "w": "numeral.com",
    "k": "Marketing Operations Manager role open",
    "desc": "Sales tax/VAT/GST compliance software"
  }
];
