import type { Question } from "./types";

export const CITIES: [name: string, lat: number, lng: number][] = [
  ["Campbell", 37.2872, -121.95],
  ["San Jose", 37.3382, -121.8863],
  ["Los Gatos", 37.2358, -121.9624],
  ["Saratoga", 37.2638, -122.023],
  ["Santa Clara", 37.3541, -121.9552],
  ["Cupertino", 37.323, -122.0322],
  ["Sunnyvale", 37.3688, -122.0363],
  ["Mountain View", 37.3861, -122.0839],
  ["Palo Alto", 37.4419, -122.143],
  ["Redwood City", 37.4852, -122.2364],
  ["San Mateo", 37.563, -122.3255],
  ["Fremont", 37.5485, -121.9886],
  ["Oakland", 37.8044, -122.2712],
  ["Berkeley", 37.8715, -122.273],
  ["San Francisco", 37.7749, -122.4194],
  ["Daly City", 37.6879, -122.4702],
  ["Hayward", 37.6688, -122.0808],
  ["Milpitas", 37.4323, -121.8996],
  ["Morgan Hill", 37.1305, -121.6544],
  ["Gilroy", 37.0058, -121.5683],
];

export const QUESTIONS: Question[] = [
  { k: "loc", t: "Where are you based?", s: "Everything else is ranked from here.", type: "loc" },
  {
    k: "max",
    t: "How far are you willing to travel?",
    s: "Each way, on a normal day.",
    type: "one",
    o: [
      ["5", "Under 5 miles", "Walking or a short bike ride"],
      ["15", "Up to 15 miles", "A 20 to 30 minute drive"],
      ["30", "Up to 30 miles", "A real commute, but doable"],
      ["50", "50 miles or more", "I'll travel if the role is right"],
    ],
  },
  {
    k: "how",
    t: "How would you get there?",
    s: "This changes how quickly distance stops being worth it.",
    type: "one",
    o: [
      ["drive", "I drive myself", ""],
      ["driven", "Someone drives me", "A parent or a lift. Shorter is much better."],
      ["transit", "Bike or public transit", "Anything far gets long fast"],
      ["none", "I'd only work remotely", ""],
    ],
  },
  {
    k: "role",
    t: "What do you want to work on?",
    s: "Pick everything that applies.",
    type: "many",
    o: [
      ["marketing", "Marketing and growth", "Content, social, SEO, ads"],
      ["ops", "Business and operations", "Whatever needs doing at a small company"],
      ["eng", "Engineering", "Writing code"],
      ["design", "Design", "Visual, brand, product"],
      ["data", "Data and analysis", "Research, spreadsheets, reporting"],
    ],
  },
  {
    k: "stage",
    t: "Where are you in school?",
    s: "",
    type: "one",
    o: [
      ["hs", "High school", ""],
      ["ug", "College", ""],
      ["grad", "Recent graduate", ""],
      ["other", "Something else", ""],
    ],
  },
  {
    k: "size",
    t: "How big a team do you want?",
    s: "Smaller usually means more responsibility and less structure.",
    type: "one",
    o: [
      ["tiny", "Under 10 people", "You'd work directly with a founder"],
      ["small", "10 to 50", "Small but with some structure"],
      ["big", "50 or more", "A real process, a recognisable name"],
      ["any", "No preference", ""],
    ],
  },
  {
    k: "mode",
    t: "In person or remote?",
    s: "",
    type: "one",
    o: [
      ["onsite", "In person", "I want to be in the room"],
      ["hybrid", "Either is fine", ""],
      ["remote", "Remote only", ""],
    ],
  },
  {
    k: "when",
    t: "When do you want to start?",
    s: "",
    type: "one",
    o: [
      ["sum27", "Summer 2027", ""],
      ["school", "During the school year", ""],
      ["asap", "As soon as possible", ""],
      ["flex", "I'm flexible", ""],
    ],
  },
  {
    k: "pay",
    t: "Does it need to be paid?",
    s: "",
    type: "one",
    o: [
      ["yes", "Yes", ""],
      ["prefer", "I'd prefer it, but no", ""],
      ["no", "Doesn't matter", ""],
    ],
  },
  {
    k: "pri",
    t: "What matters most?",
    s: "Pick up to two. These get weighted more heavily.",
    type: "many",
    max: 2,
    o: [
      ["commute", "Being close to home", ""],
      ["fit", "Doing the work I actually want", ""],
      ["size", "Team size", ""],
      ["growth", "Joining something growing fast", ""],
      ["reach", "Being able to reach a real person", "Some companies are much easier to contact"],
    ],
  },
];
