import type { Question } from "./types";

export const QUESTIONS: Question[] = [
  { k: "loc", t: "Where are you based?", s: "Everything else is ranked from here.", type: "loc" },
  {
    k: "max",
    t: "How far are you willing to travel?",
    s: "Each way, on a normal day.",
    type: "one",
    o: [
      ["5", "Under 5 miles", "Walking or a short bike ride"],
      ["15", "Up to 15 miles", "A 20 to 30 minute drive"],
      ["30", "Up to 30 miles", "A real commute, but doable"],
      ["50", "50 miles or more", "I'll travel if the role is right"],
    ],
  },
  {
    k: "how",
    t: "How would you get there?",
    s: "This changes how quickly distance stops being worth it.",
    type: "one",
    o: [
      ["drive", "I drive myself", ""],
      ["driven", "Someone drives me", "A parent or a lift. Shorter is much better."],
      ["transit", "Bike or public transit", "Anything far gets long fast"],
      ["none", "I'd only work remotely", ""],
    ],
  },
  {
    k: "role",
    t: "What do you want to work on?",
    s: "Pick everything that applies.",
    type: "many",
    o: [
      ["marketing", "Marketing and growth", "Content, social, SEO, ads"],
      ["ops", "Business and operations", "Whatever needs doing at a small company"],
      ["eng", "Engineering and tech", "Writing code, IT support"],
      ["design", "Design", "Visual, brand, product"],
      ["data", "Data and analysis", "Research, spreadsheets, reporting"],
      ["trades", "Trades and hands-on work", "Workshop, construction, mechanical, manufacturing"],
      ["healthcare", "Healthcare", "Clinics, hospitals, patient care"],
      ["hospitality", "Hospitality and food", "Restaurants, hotels, events, catering"],
      ["retail", "Retail and customer service", "Stores, customer-facing roles"],
      ["other", "Something else", "Tell us in your own words"],
    ],
  },
  {
    k: "stage",
    t: "Where are you in school?",
    s: "",
    type: "one",
    o: [
      ["hs", "High school", ""],
      ["ug", "College", ""],
      ["grad", "Recent graduate", ""],
      ["other", "Something else", ""],
    ],
  },
  {
    k: "mode",
    t: "In person or remote?",
    s: "",
    type: "one",
    o: [
      ["onsite", "In person", "I want to be in the room"],
      ["hybrid", "Either is fine", ""],
      ["remote", "Remote only", ""],
    ],
  },
  {
    k: "when",
    t: "When do you want to start?",
    s: "",
    type: "one",
    o: [
      ["sum27", "Summer 2027", ""],
      ["school", "During the school year", ""],
      ["asap", "As soon as possible", ""],
      ["flex", "I'm flexible", ""],
    ],
  },
  {
    k: "pay",
    t: "Does it need to be paid?",
    s: "",
    type: "one",
    o: [
      ["yes", "Yes", ""],
      ["prefer", "I'd prefer it, but no", ""],
      ["no", "Doesn't matter", ""],
    ],
  },
  {
    k: "pri",
    t: "What matters most?",
    s: "Pick up to two. These get weighted more heavily.",
    type: "many",
    max: 2,
    o: [
      ["commute", "Being close to home", ""],
      ["fit", "Doing the work I actually want", ""],
      ["pay", "Getting paid", ""],
    ],
  },
];
